// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserDto struct {
	Age             int    `json:"age"`
	Username        string `json:"username"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type UserDto struct {
	ID       string `json:"id"`
	Age      int    `json:"age"`
	Username string `json:"username"`
}
