// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserDto struct {
	Email           string `json:"email"`
	Firstname       string `json:"firstname"`
	Lastname        string `json:"lastname"`
	Birthdate       Date   `json:"birthdate"`
	Age             int    `json:"age"`
	Username        string `json:"username"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type UserDto struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Birthdate Date   `json:"birthdate"`
	Age       int    `json:"age"`
	Username  string `json:"username"`
}
